# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Tue May  5 18:00:47 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(584, 446)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.horizontalLayout_2.addWidget(self.searchLineEdit)
        self.searchButton = QtGui.QPushButton(self.centralwidget)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_2.addWidget(self.searchButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.userLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.userLineEdit.setInputMask("")
        self.userLineEdit.setObjectName("userLineEdit")
        self.horizontalLayout_2.addWidget(self.userLineEdit)
        self.passLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.passLineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passLineEdit.setObjectName("passLineEdit")
        self.horizontalLayout_2.addWidget(self.passLineEdit)
        self.connectButton = QtGui.QPushButton(self.centralwidget)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout_2.addWidget(self.connectButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.coursesTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.coursesTabWidget.setObjectName("coursesTabWidget")
        self.myCourses = QtGui.QWidget()
        self.myCourses.setObjectName("myCourses")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.myCourses)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.treeView_2 = QtGui.QTreeView(self.myCourses)
        self.treeView_2.setObjectName("treeView_2")
        self.verticalLayout_3.addWidget(self.treeView_2)
        self.coursesTabWidget.addTab(self.myCourses, "")
        self.allCourses = QtGui.QWidget()
        self.allCourses.setObjectName("allCourses")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.allCourses)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeView = QtGui.QTreeView(self.allCourses)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.coursesTabWidget.addTab(self.allCourses, "")
        self.verticalLayout_2.addWidget(self.coursesTabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.downloadButton = QtGui.QPushButton(self.centralwidget)
        self.downloadButton.setObjectName("downloadButton")
        self.horizontalLayout.addWidget(self.downloadButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 584, 23))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtGui.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Ouvrir = QtGui.QAction(MainWindow)
        self.action_Ouvrir.setObjectName("action_Ouvrir")
        self.action_Fermer = QtGui.QAction(MainWindow)
        self.action_Fermer.setObjectName("action_Fermer")
        self.action_Update_db = QtGui.QAction(MainWindow)
        self.action_Update_db.setObjectName("action_Update_db")
        self.menuFichier.addAction(self.action_Ouvrir)
        self.menuFichier.addAction(self.action_Update_db)
        self.menuFichier.addAction(self.action_Fermer)
        self.menubar.addAction(self.menuFichier.menuAction())

        self.retranslateUi(MainWindow)
        self.coursesTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.searchLineEdit, self.searchButton)
        MainWindow.setTabOrder(self.searchButton, self.userLineEdit)
        MainWindow.setTabOrder(self.userLineEdit, self.passLineEdit)
        MainWindow.setTabOrder(self.passLineEdit, self.connectButton)
        MainWindow.setTabOrder(self.connectButton, self.downloadButton)
        MainWindow.setTabOrder(self.downloadButton, self.treeView)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Chamilo", None, QtGui.QApplication.UnicodeUTF8))
        self.searchLineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "LOG, Algo...", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.userLineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "G12345", None, QtGui.QApplication.UnicodeUTF8))
        self.passLineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "p4ssw0rd", None, QtGui.QApplication.UnicodeUTF8))
        self.connectButton.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.coursesTabWidget.setTabText(self.coursesTabWidget.indexOf(self.myCourses), QtGui.QApplication.translate("MainWindow", "Mes cours", None, QtGui.QApplication.UnicodeUTF8))
        self.coursesTabWidget.setTabText(self.coursesTabWidget.indexOf(self.allCourses), QtGui.QApplication.translate("MainWindow", "Tous les cours", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadButton.setText(QtGui.QApplication.translate("MainWindow", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFichier.setTitle(QtGui.QApplication.translate("MainWindow", "Fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Ouvrir.setText(QtGui.QApplication.translate("MainWindow", "&Ouvrir", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Fermer.setText(QtGui.QApplication.translate("MainWindow", "&Fermer", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Update_db.setText(QtGui.QApplication.translate("MainWindow", "&Update db", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Update_db.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+U", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

